Repository hmcts/draft-store, pull requests merged in 2019-09, with the labels that each got.

#354 Fix owasp dep check failure, bumping checkstyle
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: ns:draft-store-service-pr-354

#358 fixing owasp failure
  build.gradle
Labels: ns:draft-store-service-pr-358

#348 Cleanup ase
  infrastructure/.gitignore
  infrastructure/aat.tfvars
  infrastructure/alert_bad_response_code.tf
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:draft-store-service-pr-348

#364 Making env variables dynamic to reduce variables overriden in each env
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/values.aat.template.yaml
  charts/draft-store-service/values.preview.template.yaml
  charts/draft-store-service/values.yaml
Labels: ns:draft-store-service-pr-364

#374 fix owasp issue
  config/owasp/suppressions.xml
Labels: ns:draft-store-service-pr-374

#375 Bumping java chart
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/requirements.yaml
Labels: ns:draft-store-service-pr-375

#376 Revert "Bump org.flywaydb.flyway from 5.2.4 to 6.0.2"
  build.gradle
Labels: ns:draft-store-service-pr-376

#388 Bumping to latest java chart
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/requirements.yaml
  config/owasp/suppressions.xml
Labels: ns:draft-store-service-pr-388

#390 Fix image in published chart
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/values.yaml
Labels: ns:draft-store-service-pr-390

#392 Move to latest distroless docker image
  Dockerfile
  lib/applicationinsights-agent-2.3.1.jar
Labels: ns:draft-store-service-pr-392

#397 Fix perftest objectId
  build.gradle
  infrastructure/perftest.tfvars
Labels: ns:draft-store-service-pr-397

#396 Adding appinsights to keyvault and bumping chart
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/requirements.yaml
  charts/draft-store-service/values.aat.template.yaml
  charts/draft-store-service/values.preview.template.yaml
  charts/draft-store-service/values.yaml
  config/owasp/suppressions.xml
  infrastructure/main.tf
Labels: ns:draft-store-service-pr-396

#399 Adding appinsights key as secret to chart
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:draft-store-service-pr-399
