Repository hmcts/draft-store, pull requests merged in 2019-06, with the labels that each got.

#308 Update owasp dependency check to version 5
  Jenkinsfile_CNP
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:draft-store-service-pr-308

#305 Add config for perftest
  infrastructure/main.tf
  infrastructure/perftest.tfvars
Labels: ns:draft-store-service-pr-305

#304 Update travis badge
  README.md
Labels: ns:draft-store-service-pr-304

#315 Migrate to hmctspublic registry
  Dockerfile
Labels: ns:draft-store-service-pr-315
