Repository hmcts/draft-store, pull requests merged in 2019-08, with the labels that each got.

#333 managed identiy for perftest AKS
  infrastructure/perftest.tfvars
Labels: ns:draft-store-service-pr-333

#337 Upgrade jackson databind
  build.gradle
Labels: ns:draft-store-service-pr-337

#339 Add prometheus metrics
  build.gradle
  charts/draft-store-service/requirements.yaml
  docker-compose.yml
  src/main/resources/application.yaml
Labels: ns:draft-store-service-pr-339

#343 Bumping java chart
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/requirements.yaml
Labels: ns:draft-store-service-pr-343

#329 Go live on AKS
  Jenkinsfile_CNP
Labels: ns:draft-store-service-pr-329

#344 Update Jenkinsfile_parameterized
  Jenkinsfile_parameterized
Labels: ns:draft-store-service-pr-344

#349 Fix deprecation warnings
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  infrastructure/output.tf
Labels: ns:draft-store-service-pr-349
