Repository hmcts/draft-store, pull requests merged in 2019-10, with the labels that each got.

#401 Upgrade applicationinsights jars
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
  web.config
Labels: ns:draft-store-service-pr-401

#403 fixing app insights
  src/main/resources/bootstrap.yaml
Labels: ns:draft-store-service-pr-403

#424 Use datasource default settings
  src/main/resources/application.yaml
Labels: ns:draft-store-service-pr-424
