Repository hmcts/draft-store, pull requests merged in 2019-02, with the labels that each got.

#260 Use the new heatlh-starter module
  build.gradle
  charts/draft-store-service/values.template.yaml
  src/smokeTest/java/uk/gov/hmcts/reform/draftstore/ApplicationSmokeTest.java
Labels: ns:draft-store-service-pr-260

#259 Update image to alpine 3.9 jre 1.8-191
  Dockerfile
Labels: ns:draft-store-service-pr-259

#261 Remove unneeded env var
  Dockerfile
Labels: ns:draft-store-service-pr-261

#263 Move to new chart
  charts/draft-store-service/requirements.yaml
  charts/draft-store-service/values.template.yaml
Labels: ns:draft-store-service-pr-263

#264 bug fix
  infrastructure/main.tf
Labels: ns:draft-store-service-pr-264

#258 RPE-345 Use PAAS database in the application
  infrastructure/main.tf
Labels: ns:draft-store-service-pr-258, pinned

#266 Upgraded to latest logging n chart
  build.gradle
  charts/draft-store-service/requirements.yaml
  docker-compose.yml
Labels: ns:draft-store-service-pr-266
