Repository hmcts/draft-store, pull requests merged in 2020-10, with the labels that each got.

#729 revert infra branch to master
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-729

#732 test terraform manager
  .github/renovate.json
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-732

#733 Remove wild card to test renovate
  infrastructure/state.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-733

#741 Add dependencies labels to renovate PRs
  .github/renovate.json
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-741

#747 Add v11 postgresDB
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-747

#749 Add v11 postgresDB
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-749

#754 TA-83: Initial code for Provider test for Divorce
  Jenkinsfile_CNP
  build.gradle
  config/owasp/suppressions.xml
  src/contractTest/java/uk/gov/hmcts/reform/draftstore/controllers/DivorceDraftControllerProviderTest.java
  src/contractTest/java/uk/gov/hmcts/reform/draftstore/controllers/DraftControllerProviderTestConfiguration.java
  src/contractTest/resources/application.yml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-754
