Repository hmcts/draft-store, pull requests merged in 2020-05, with the labels that each got.

#608 Upgrade dependencies.
  Jenkinsfile_CNP
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, rel:draft-store-service-pr-608

#616 Update dependencies. Clean up suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, rel:draft-store-service-pr-616

#621 Bump base chart
  .gitignore
  charts/draft-store-service/Chart.yaml
Labels: ns:rpe, rel:draft-store-service-pr-621
