Repository hmcts/draft-store, pull requests merged in 2020-08, with the labels that each got.

#675 Test docker inbound-agent build process
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-675

#676 Revert docker agent test change
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-676

#680 Fix branch
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-680

#694 Disable gssenc option for postgresql jdbc driver
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/values.yaml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-694
