Repository hmcts/draft-store, pull requests merged in 2020-06, with the labels that each got.

#630 Add renovate for helm requirements
  .github/renovate.json
  renovate.json
Labels: ns:rpe, rel:draft-store-service-pr-630

#632 Remove tilde from requirements
  charts/draft-store-service/Chart.yaml
Labels: ns:rpe, rel:draft-store-service-pr-632

#644 Update to java 11
  .travis.yml
  Dockerfile
  build.gradle
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-644
