Repository hmcts/draft-store, pull requests merged in 2020-11, with the labels that each got.

#779 Test permissions are in place for aad-auth postgres
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-779

#770 Move to master cnp-module-keyvault
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-770

#786 DTSPO-264 Set name for postgres DB
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-786

#789 Revert "DTSPO-264 Set name for postgres DB"
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-789
