Repository hmcts/draft-store, pull requests merged in 2020-09, with the labels that each got.

#699 update chart-java
  charts/draft-store-service/Chart.yaml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-699

#701 fix name for csi driver
  charts/draft-store-service/Chart.yaml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-701

#702 Upgrade terraform provider
  .terraform-version
  infrastructure/alert_bad_response_code.tf
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/test_config.tf
  infrastructure/variables.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-702

#704 Fix quality gate error
  src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-704

#705 Fix quality gate error (as sonar likes?)
  src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-705

#706 Fix quality gate error (sonar driven syntax)
  src/main/java/uk/gov/hmcts/reform/draftstore/data/DraftStoreDao.java
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-706

#707 Fixes for terraform provider upgrade
  infrastructure/state.tf
  infrastructure/versions.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-707

#708 Fixes for terraform provider upgrade
  infrastructure/.terraform-version
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-708

#709 Fix appinsights tf application_type
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-709

#718 Test parallel image + test image build
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-718

#724 to test uninstall of staging hr after testing
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-724
