Repository hmcts/draft-store, pull requests merged in 2020-07, with the labels that each got.

#656 Bump tomcat version for CVEs
  build.gradle
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-656

#669 Build using jenkins docker agent
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-669

#672 Revert to Jenkins master branch
  Jenkinsfile_CNP
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-672

#673 Test jenkins pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-673

#674 Revert to master branch pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-674
