Repository hmcts/draft-store, pull requests merged in 2023-05, with the labels that each got.

#1322 DTSPO-13832 - remove single server
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, destroy, rel:draft-store-service-pr-1322

#1326 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1326

#1336 DTSPO-13832 - Update db values to flexible server
  charts/draft-store-service/Chart.yaml
  charts/draft-store-service/values.yaml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1336
