Repository hmcts/draft-store, pull requests merged in 2023-06, with the labels that each got.

#1337 Update renovate config
  .github/renovate.json
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1337

#1343 DTSPO-13832 - Add depends_on for app insights
  infrastructure/alert_bad_response_code.tf
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rpe, prd:draft-store, destroy, rel:draft-store-service-pr-1343

#1345 DTSPO-13832 - remove allow nested resource deletion
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, add-or-update, rel:draft-store-service-pr-1345

#1352 Sample health requests aggressively
  lib/applicationinsights.json
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1352
