Repository hmcts/draft-store, pull requests merged in 2023-01, with the labels that each got.

#1194 Update suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1194

#1196 Try downgrading tomcat to see if it fixes issue on AAT
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1196

#1205 Add regex manager
  .github/renovate.json
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1205
