Repository hmcts/draft-store, pull requests merged in 2023-02, with the labels that each got.

#1206 Provision v14 DB for DraftStore
  infrastructure/.terraform-version
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, add-or-update, rel:draft-store-service-pr-1206

#1221 Provision v14 DB for DraftStore (#1206)
  infrastructure/.terraform-version
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1221

#1224 DTSPO-11969 - Add expiresAfter in sbox
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  infrastructure/.gitignore
  infrastructure/alert_bad_response_code.tf
Labels: ns:rpe, prd:draft-store, destroy, rel:draft-store-service-pr-1224

#1226 DTSPO-11969 - Remove expiresAfter in sbox
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1226
