Repository hmcts/draft-store, pull requests merged in 2023-07, with the labels that each got.

#1368 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1368

#1380 DTSPO-14238 Migrate to workspace AI
  infrastructure/app-insights.tf
  infrastructure/main.tf
Labels: ns:rpe, prd:draft-store, add-or-update, rel:draft-store-service-pr-1380

#1385 Remove logging version - already defined and using latest version
  build.gradle
Labels: ns:rpe, prd:draft-store, rel:draft-store-service-pr-1385
